name: Processar Metadados de Vídeos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Passo 3: Instalar dependências (js-yaml)
      - name: Instalar js-yaml
        run: npm install js-yaml

      # Passo 4: Validar o arquivo YAML de metadados
      - name: Validar YAML
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');

            try {
              const filePath = 'docs/metadata/videos.yml'; // Caminho do arquivo YAML
              const fileContents = fs.readFileSync(filePath, 'utf8');
              const data = yaml.load(fileContents);

              console.log('Arquivo YAML válido!');
              console.log(data);
            } catch (e) {
              console.error('Erro no arquivo YAML:', e.message);
              process.exit(1); // Falha no fluxo de trabalho
            }

      # Passo 5: Executar um script personalizado (opcional)
      - name: Executar script personalizado
        run: |
          echo "Processando metadados de vídeos..."
          # Adicione aqui comandos personalizados, como processar os metadados.
          # Exemplo: python scripts/process_metadata.py
